language: csharp

script:
  - ./build.sh

deploy:
  provider: releases
  api_key: 2d35039cca6eebcf800c280dd5d82dd1931aecc7 
  file_glob: true
  file: ./build/*.{dll}
  skip_cleanup: true
  on:
    tags: true