language: csharp
script:
- "./build.sh Deploy"
deploy:
  provider: releases
  api_key:
    secure: iYaHgRg0Sl3hbVpa8qTb9MZWiCTMCUTwIPghJ959B39ctp+BEu5BZw10W82RxWLq3mpM6GpqzmRLnf6Ijb6Psq5vihTfkEFIimbMPcVZHgTiD5tndeLfQU1GhylhiZ0KWzdEoNTIG8E3Zj5OB4kglssoLpI4UutuA/0fUFFQ9sAoJq7lOCIRYjzTwQiuVwVoXu5kFEEltv1MheWfugyQoJyg7xrWl+qplRXGciXEHPFkrQEo7RRRfzA2u6Mc6CqvlFo8DMUZU9ZDUpk9vW2ORtWmB7vKwQbVoKH5eu9ztMhbe23/YXIMbzyQ4uVmgeujh/hMZ/QmmNsR/14g2ruDzosmatw2tsERol+7lDoWU0VhavR5VbydGUZNNZCzvtPldDI7FaFmhfPKu+zBZ2yqguS2VAy1ujMgtuAGX1FAk/O3LAR3ApnOl7uAyMWTUE85XLMiiYtEpalBIoDgySIgVir2zl+IZwAd+pZXLlEU1r0BlSSJE7+b8Y73V1m4un38j2PXngE7hKY4jUl6burRjY4Jdi4LT7xHEqGyynsHh252Y6QF/GOXcZJ5UwviI/eKYPVj7AWs4/+OuCCaTS6nDkrN0Cs03F8K7yPIVekFYGKgMWO4UffNVuUzlcoYqLbfVuN7ygYs4cM8JB5Kl3ihj4oeJv5IwT0byTroGZmPAP0=
  file_glob: true
  file: "./deploy/*.{zip}"
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: kbKcLix+qOyMBzvSclenNpR0oxzOU/GJN4Nll0CuO5R8cIfgh8yksi/bQTzK21HHeWpRNURmt3n5fBUSgsnGxVdZiiXfudXG6xX8eVBm/KteL04oH06XSIIcZQRBHSVrPLhSgvyIt9ppFj8CQG0qsh8Famtoe1aq4pGOFQePKZ2yqeAhO6t5KISnFOk0dfpJWPoF0mXQVZAJJ9wD7eoRheuI0UykeEA5yUPKrtiD1ZgpdbbnTsUoIO1Eb9xtu0kQhy8rluPkc2qymn0aADDBeITdGArbL3xjG45FYqB+VC/SaEvOraIi4ELk/qecGGX1X14dfKdVCSKqSrNAqPEZ09a0ntVoFmmox8QU1ih0JA8uqB4WoyNOZ41MareF1ts3PgSr0hAn8zMe3k7bD98RnF+5QFGCaZYRcn1/O61E7LO5pzoDhXQ8/GuPlCEv8VskjYKBgTs1bhrT5wWpIeiJUh+uOIpehy0ndbULvzfw3ho/19S0tptM5wCHMIQXsedpmAuaK7MyKMIy3Vtp+dWpDM+TOBIzpH1LA2UyLfuLEEk05c+QrexrYDXe57iU7d+Ui9vL72EFTmL0plKRLCGbye4uv8jbM7dFek1Zgk37K4DWZlkC2b1CLx6ZgrB0ewXxnn4qFJqdlk1xQS4E5wazUFx5dC8ZZDPz9G4yAI/BRPs=
